PK integrals: corrections after rebasing.
Automatic selection of PK algorithm implemented as well.
PK does not write the integral file now, so for post-SCF methods
which need it, the Python driver calls MintsHelper.
Exception: stability code which is directly within SCF.